<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;1573;1591</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;1573;1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Portable.Xaml" />
    <PackageReference Include="MonoGame.Content.Builder.Task" />
    <PackageReference Include="MonoGame.Extended" />
    <PackageReference Include="MonoGame.Extended.Content.Pipeline" />
    <PackageReference Include="MonoGame.Framework.DesktopGL">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Prism.Core" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MGUI.Shared\MGUI.Shared.csproj" />
  </ItemGroup>
</Project>
